### ISSUE TITLE
Json Deserialize error.

### ISSUE THREAD

**Issue by erijpkema** [matrix-org/prometheus-cachet-glue#6]
I'm not quite sure if this is a bug or a misconfiguration on my part. Perhaps you can clarify this. 
I'm getting the following warning in stdout of the prometheus-cachet-glue container. I'm running a docker image built from the develop branch. 

```
[2018-10-04 06:55:53][WARN][actix_web::pipeline] Error occured during request handling: Json deserialize error: missing field `component` at line 1 column 358
```

This is a fragment of my alertmanager's config.yml.
```
route:
    repeat_interval: 4h 
    group_interval: 30m
    receiver: 'default-slack'
    routes:
    - receiver: 'peregrine-slack'
      match:
        env: peregrine
      continue: true
    - receiver: 'statuspage'
      match:
        env: peregrine
   
receivers:

    - name: 'statuspage'
      webhook_configs:
          - send_resolved: true
            url: 'http://prometheus-cachet-glue:8888'
```
